version: '3.5'
services:
  peer1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8080

  peer2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - 8082:8080

  peer3:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - 8083:8080

  peer4:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - 8084:8080

networks:
  default:
    name: g4blockchain
    driver: bridge
